site_name:           ADoSnipsTemplate
repo_url:            https://github.com/andreasdominik/ADoSnipsTemplate.git
site_description:    Description
site_author:         Andreas Dominik
theme:               readthedocs

markdown_extensions:
    - codehilite
    - extra
    - tables
    - fenced_code
#    - mdx_math # For LaTeX

extra_css:
    - assets/Documenter.css

extra_javascript:
    - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML
    - assets/mathjaxhelper.js

docs_dir: 'build'

pages:
  - Introduction: index.md
  - Installation: inst.md
  - Skills: makeskill.md
  - API documemntation: api/api.md
  - License: LICENSE.md
